version: "3.9"
services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    ports: [ "5433:5432" ]
    volumes:
      - ./postgres:/data/postgres
    restart: unless-stopped
  #redis
  redis:
    container_name: book-redis
    platform: linux/x86_64
    image: docker.io/bitnami/redis:7:0
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    networks:
      - redis-network
    env_file: [ .env ]  
  
  redis-commander:
    container_name: book-redis-commander
    image: rediscommander/redis-commander:latest
    platform: linux/x86_64
    restart: always
    enviroment:
      REDIS_HOSTS: redis
      REDIS_HOST: redis
      REDIS_PORT: redis:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports: {}